name: flutter_getui
description: getui plugin for flutter, only Android and IOS are supported
version: 1.1.3
repository: https://github.com/Wayaer/flutter_getui.git

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fl.getui
        pluginClass: GeTuiPlugin
      ios:
        pluginClass: GeTuiPlugin
